version: 2.1

jobs:
  my-job:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - run: exit 1
      - run:
          command: echo Hello, Error!
          when: on_fail

workflows:
  my-workflow:
    jobs:
      - my-job
