version: 2.1

commands: 
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps: 
      - print_pipeline_id

workflows:
  my-workflow:
    jobs:
      - my-job
